{
 "title": "Frugalos",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "frugalos_build" },
   {
    "name": "host",
    "query": "frugalos_build { job = \"$job\" }"
   },
   {
    "name": "device_count",
    "query": "query_result(count(cannyls_storage_header{device != \"system\", job=\"$job\"}))"
   }
  ]
 },
 "panels": [
  { "title": "現況概要", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ノード数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job = \"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "デバイス数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cannyls_storage_header{job = \"$job\", device != \"system\"})"
    }
   ]
  },
  {
   "title": "オブジェクト数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(frugalos_mds_objects{job = \"$job\", role=\"Leader\"})"
    }
   ]
  },
  {
   "title": "ストレージ容量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_data_region_capacity_bytes{job = \"$job\"})"
    }
   ]
  },
  {
   "title": "ストレージ使用率（平均）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(cannyls_data_allocator_allocated_bytes_total{job = \"$job\"}) - sum(cannyls_data_allocator_released_bytes_total{job = \"$job\"})) / sum(cannyls_data_region_capacity_bytes{job = \"$job\"})"
    }
   ]
  },
  {
   "title": "ストレージ使用率（最大）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((sum by(device)(cannyls_data_allocator_allocated_bytes_total{job = \"$job\"}) - sum by(device)(cannyls_data_allocator_released_bytes_total{job = \"$job\"})) / sum by(device)(cannyls_data_region_capacity_bytes{job = \"$job\"}))"
    }
   ]
  },
  {
   "title": "CPU使用率（平均）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"($host).*\",mode=\"idle\"}[3m]))"
    }
   ]
  },
  {
   "title": "CPU使用率（最大）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(1 - avg by(instance)(irate(node_cpu_seconds_total{instance=~\"($host).*\",mode=\"idle\"}[3m])))"
    }
   ]
  },
  {
   "title": "ディスクI/O使用率（平均）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(topk($device_count, rate(node_disk_io_time_seconds_total{instance=~\"($host).*\"}[3m])))"
    }
   ]
  },
  {
   "title": "ディスクI/O使用率（最大）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(topk($device_count, rate(node_disk_io_time_seconds_total{instance=~\"($host).*\"}[3m])))"
    }
   ]
  },
  {
   "title": "メモリ使用率（平均）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(1 - node_memory_MemAvailable_bytes{instance =~ \"($host).*\"} / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "メモリ使用率（最大）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(1 - node_memory_MemAvailable_bytes{instance =~ \"($host).*\"} / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "ディスク書き込み量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance =~ \"($host).*\"}[3m]))"
    }
   ]
  },
  {
   "title": "ディスク読み込み量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance =~ \"($host).*\"}[3m]))"
    }
   ]
  },
  {
   "title": "ネットワーク出力帯域",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max by(instance)(rate(node_network_transmit_bytes_total{instance =~ \"($host).*\"}[3m]))) * 8"
    }
   ]
  },
  {
   "title": "ネットワーク入力帯域",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max by(instance)(rate(node_network_receive_bytes_total{instance =~ \"($host).*\"}[3m]))) * 8"
    }
   ]
  },
  {
   "title": "エラーログ出力数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(log_records_total{job = \"$job\", level =~ \"error|critical\"}[2m]))"
    }
   ]
  },
  {
   "title": "デバイスキュー長",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_device_enqueued_commands_total{job = \"$job\"} - cannyls_device_dequeued_commands_total{job = \"$job\"})"
    }
   ]
  },
  {
   "title": "タスクキュー長",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (tasque_enqueued_tasks_total{job = \"$job\"} - tasque_dequeued_tasks_total{job = \"$job\"})"
    }
   ]
  },
  {
   "title": "ピーク時概要",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率（平均）",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"($host).*\",mode=\"idle\"}[5m]))"
      }
     ]
    },
    {
     "title": "CPU使用率（最大）",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(1 - avg by(instance)(irate(node_cpu_seconds_total{instance=~\"($host).*\",mode=\"idle\"}[5m])))"
      }
     ]
    },
    {
     "title": "ディスクI/O使用率（平均）",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "expr": "avg(topk($device_count, rate(node_disk_io_time_seconds_total{instance=~\"($host).*\"}[5m])))"
      }
     ]
    },
    {
     "title": "ディスクI/O使用率（最大）",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(topk($device_count, rate(node_disk_io_time_seconds_total{instance=~\"($host).*\"}[5m])))"
      }
     ]
    },
    {
     "title": "デバイスキュー長",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(cannyls_device_enqueued_commands_total{job = \"$job\"} - cannyls_device_dequeued_commands_total{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "タスクキュー長",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum (tasque_enqueued_tasks_total{job = \"$job\"} - tasque_dequeued_tasks_total{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "ディスク書き込み量",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "Bps",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance =~ \"($host).*\"}[5m]))"
      }
     ]
    },
    {
     "title": "ディスク読み込み量",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "Bps",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance =~ \"($host).*\"}[5m]))"
      }
     ]
    },
    {
     "title": "ネットワーク出力帯域",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "bps",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(max by(instance)(rate(node_network_transmit_bytes_total{instance =~ \"($host).*\"}[5m]))) * 8"
      }
     ]
    },
    {
     "title": "ネットワーク入力帯域",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "bps",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(max by(instance)(rate(node_network_receive_bytes_total{instance =~ \"($host).*\"}[5m]))) * 8"
      }
     ]
    }
   ]
  },
  {
   "title": "構成情報",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "frugalosのバージョン",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(version)(frugalos_build{job = \"$job\"})",
       "legendFormat": "v{{ version }}"
      }
     ]
    },
    {
     "title": "ノード毎のデバイス数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(instance)(cannyls_storage_header{job = \"$job\", device != \"system\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "起動後に停止したデバイス群",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cannyls_device_status{job = \"$job\"} == 0",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ストレージ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "オブジェクト数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(frugalos_mds_objects{job = \"$job\", role=\"Leader\"})",
       "legendFormat": "全体"
      }
     ]
    },
    {
     "title": "秒間のデータ増減",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_data_allocator_allocated_bytes_total{job = \"$job\", phase = \"running\"}[3m]))",
       "legendFormat": "追加量"
      },
      {
       "expr": "sum(rate(cannyls_data_allocator_released_bytes_total{job = \"$job\"}[3m]))",
       "legendFormat": "削除量"
      }
     ]
    },
    {
     "title": "ストレージ使用量",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_data_allocator_allocated_bytes_total{job = \"$job\"}) - sum(cannyls_data_allocator_released_bytes_total{job = \"$job\"})",
       "legendFormat": "全体"
      }
     ]
    },
    {
     "title": "ストレージ使用量（ノード毎）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(cannyls_data_allocator_allocated_bytes_total{job = \"$job\"}) - sum by(instance)(cannyls_data_allocator_released_bytes_total{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU、ディスク、メモリ、ネットワーク",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{instance=~\"($host).*\",mode=\"idle\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "ディスクI/O使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by(instance)(topk($device_count, irate(node_disk_io_time_seconds_total{instance=~\"($host).*\"}[3m])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "メモリ使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - max by (instance)(avg_over_time(node_memory_MemAvailable_bytes{instance=~\"($host).*\"}[3m]) / node_memory_MemTotal_bytes)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "frugalosプロセスのメモリ使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(node)(label_replace(process_resident_memory_bytes{job = \"$job\"}, \"node\", \"$1\", \"instance\", \"(.*):.*\")) / sum by(node)(label_replace(node_memory_MemTotal_bytes, \"node\", \"$1\", \"instance\", \"(.*):.*\"))",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "ネットワークの出力帯域",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "max by(instance)(rate(node_network_transmit_bytes_total{instance =~ \"($host).*\"}[3m])) * 8",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "ネットワークの入力帯域",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "max by (instance)(rate(node_network_receive_bytes_total{instance =~ \"($host).*\"}[3m])) * 8",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "ディスク読み込み量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance =~ \"($host).*\"}[3m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "ディスク書き込み量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance =~ \"($host).*\"}[3m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "秒間HTTPリクエスト数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fibers_http_server_handler_requests_total{job = \"$job\"}[3m])) by (method, path)",
       "legendFormat": "{{ method }} {{ path }}"
      }
     ]
    },
    {
     "title": "秒間HTTPリクエスト数(応答ステータス別)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fibers_http_server_handler_requests_total{job = \"$job\"}[3m])) by (status) != 0",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "オブジェクトGETの応答時間（パーセンタイル）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"GET\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"GET\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"GET\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "オブジェクトPUTの応答時間（パーセンタイル）",
     "type": "graph",
     "description": "HTTPリクエストおよびレスポンスのボディの送受信時間は含まれない",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"PUT\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"PUT\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fibers_http_server_handler_request_duration_seconds_bucket{job = \"$job\", method = \"PUT\", path = \"/v1/buckets/*/objects/*\"}[3m])) by (le))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "HTTPサーバエラー数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fibers_http_server_errors_total{job = \"$job\"}[3m])) by (phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "新規接続TCPクライアント数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fibers_http_server_connected_tcp_clients_total{job = \"$job\"}[3m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "接続中TCPクライアント数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fibers_http_server_connected_tcp_clients_total{job = \"$job\"} - fibers_http_server_disconnected_tcp_clients_total{job = \"$job\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "タスクキュー",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ワーカスレッド数",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(tasque_workers{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "ワーカスレッド数再起動数",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(tasque_worker_restarts_total{job = \"$job\"}[1h]))"
      }
     ]
    },
    {
     "title": "タスク実行時間（パーセンタイル）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(tasque_task_duration_seconds_bucket{job = \"$job\"}[3m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(tasque_task_duration_seconds_bucket{job = \"$job\"}[3m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tasque_task_duration_seconds_bucket{job = \"$job\"}[3m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tasque_task_duration_seconds_bucket{job = \"$job\"}[3m])) by (le))",
       "legendFormat": "100%"
      }
     ]
    },
    {
     "title": "タスクキューの長さ（実行待ちのタスク数）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(tasque_enqueued_tasks_total{job = \"$job\"} - tasque_dequeued_tasks_total{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "新規タスク数/秒",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(rate(tasque_enqueued_tasks_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ストレージ詳細",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "ジャーナル領域使用量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_journal_queue_consumed_bytes_total{job = \"$job\"}) - sum(cannyls_journal_queue_released_bytes_total{job = \"$job\"})",
       "legendFormat": "合計"
      }
     ]
    },
    {
     "title": "ジャーナル領域使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(cannyls_journal_queue_consumed_bytes_total{job = \"$job\"}) - sum(cannyls_journal_queue_released_bytes_total{job = \"$job\"})) / sum(cannyls_journal_queue_capacity_bytes{job = \"$job\"})",
       "legendFormat": "平均"
      },
      {
       "expr": "max((sum by(device)(cannyls_journal_queue_consumed_bytes_total{job = \"$job\"}) - sum by(device)(cannyls_journal_queue_released_bytes_total{job = \"$job\"})) / sum by(device)(cannyls_journal_queue_capacity_bytes{job = \"$job\"}))",
       "legendFormat": "最大"
      }
     ]
    },
    {
     "title": "レコード追記数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(cannyls_journal_queue_enqueued_records_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "レコード削除数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(cannyls_journal_queue_dequeued_records_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "デバイスへの秒間コマンド発行数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(command)(rate(cannyls_device_enqueued_commands_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "デバイスの処理待ちコマンド数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(cannyls_device_enqueued_commands_total{job = \"$job\"} - cannyls_device_dequeued_commands_total{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "デバイスのデータ領域割当用フリーリストの断片数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_data_allocator_inserted_free_portions_total{job = \"$job\"} - cannyls_data_allocator_removed_free_portions_total{job = \"$job\"})",
       "legendFormat": "全体"
      }
     ]
    },
    {
     "title": "実行失敗コマンド数／秒",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(command)(rate(cannyls_device_failed_commands_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "データ領域アロケータへの要求数／秒",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_data_allocator_allocated_portions_total{job = \"$job\"}[3m]))",
       "legendFormat": "割当要求発行数"
      },
      {
       "expr": "sum(rate(cannyls_data_allocator_released_portions_total{job = \"$job\"}[3m]))",
       "legendFormat": "解放要求発行数"
      }
     ]
    },
    {
     "title": "バックグランドタスクの実行数/秒",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_device_side_jobs_total{job = \"$job\"}[3m]))",
       "legendFormat": "全体"
      }
     ]
    },
    {
     "title": "ジャーナルキュー内のレコード数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(type)(cannyls_journal_queue_enqueued_records_total{job = \"$job\"}) - sum by(type)(cannyls_journal_queue_dequeued_records_total{job = \"$job\"})",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Lump数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_storage_put_lumps_total{job = \"$job\"}) - sum(cannyls_storage_delete_lumps_total{job = \"$job\"})",
       "legendFormat": "全体"
      }
     ]
    },
    {
     "title": "実行失敗コマンド数／秒 (デバイス別)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(device)(rate(cannyls_device_failed_commands_total{job = \"$job\"}[3m])) != 0",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "GCレコードの秒間エンキュー・デキュー数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(cannyls_journal_region_gc_dequeued_records_total{job = \"$job\"}[3m])) ",
       "legendFormat": "dequeue"
      },
      {
       "expr": "sum (rate(cannyls_journal_region_gc_enqueued_records_total{job = \"$job\"}[3m])) ",
       "legendFormat": "enqueue"
      }
     ]
    }
   ]
  },
  {
   "title": "ログ出力",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "ログ出力数（深刻度別）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(log_records_total{job = \"$job\"}[2m])) by (level)",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "ログ出力数（ノード別）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(log_records_total{job = \"$job\"}[2m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "frugalos詳細",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "シンクロナイザのキューの長さ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(type)(frugalos_synchronizer_enqueued_items{job = \"$job\"} - frugalos_synchronizer_dequeued_items{job = \"$job\"})",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "シンクロナイザのアイテムの秒間の追加削除数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(type)(rate(frugalos_synchronizer_enqueued_items{job = \"$job\"}[3m]))",
       "legendFormat": "[enq] {{ type }}"
      },
      {
       "expr": "sum by(type)(rate(frugalos_synchronizer_dequeued_items{job = \"$job\"}[3m]))",
       "legendFormat": "[deq] {{ type }}"
      }
     ]
    },
    {
     "title": "オブジェクト数（ノード毎）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(frugalos_mds_objects{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Lump数（ノード毎）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(cannyls_storage_put_lumps_total{job = \"$job\"}) - sum by(instance)(cannyls_storage_delete_lumps_total{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raftキュー長",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(frugalos_mds_proposal_queue_len{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "スナップショット取得数/秒",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(frugalos_mds_snapshots_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "スナップショット書き込みバイト数/秒",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(frugalos_mds_snapshot_bytes_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "内部RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "送信メッセージキュー長",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(fibers_rpc_channel_enqueued_outgoing_messages_total{job = \"$job\"} - fibers_rpc_channel_dequeued_outgoing_messages_total{job = \"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "メッセージドロップ数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(fibers_rpc_client_discarded_outgoing_messages_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC処理数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (procedure)(rate(fibers_rpc_handler_rpc_total{job = \"$job\"}[3m]) != 0)",
       "legendFormat": "{{ procedure }}"
      }
     ]
    },
    {
     "title": "Raftメッセージ送信数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(raft_io_rpc_send_messages_total{job = \"$job\"}[3m]) != 0)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "RPCチャンネル生成数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(increase(fibers_rpc_channel_created_channels_total{job = \"$job\"}[3m]) != 0)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "メッセージ送信数",
     "type": "graph",
     "description": "※ 通信先サーバの停止直後に送信数が急増して見えることがあるが、たいていはprometheusの集計上の問題なので注意（他のグラフも参照しつつ実際に増えていたのかどうかを判断する必要がある）",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(fibers_rpc_channel_dequeued_outgoing_messages_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Yield数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(fibers_rpc_channel_fiber_yielded_total{job = \"$job\"}[3m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "非同期送受信数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(fibers_rpc_channel_async_incoming_messages_total{job = \"$job\"}[3m]))",
       "legendFormat": "非同期受信"
      },
      {
       "expr": "sum (rate(fibers_rpc_channel_async_outgoing_messages_total{job = \"$job\"}[3m]))",
       "legendFormat": "非同期送信"
      }
     ]
    }
   ]
  }
 ]
}